# Generated by Django 5.2 on 2025-05-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbanners',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='indexbanners',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
