# Generated by Django 5.2 on 2025-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
