# Generated by Django 5.2 on 2025-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_module', '0002_books_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.AddField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='catalogue_module.categories', verbose_name='Категории'),
        ),
    ]
